require:
  - rubocop-rails
  - rubocop-rspec

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "config/**/*"
    - "db/**/*"
    - "node_modules/**/*"
    - "log/**"
    - "public/**"
    - "storage/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
