require:
  - rubocop-rails
  - rubocop-rspec


Bundler/OrderedGems:
    Enabled: false

Style/Documentation:
    Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'log/**'
    - 'public/**'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
